# Generated by Django 5.2.3 on 2025-07-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
