# Generated by Django 5.2.3 on 2025-07-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkRecommendation',
        ),
    ]
