# Generated by Django 5.2.3 on 2025-08-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('payment_processing', 'Обработка платежа'), ('paid', 'Оплачено'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('waiting_payment', 'Ожидание оплаты'), ('funds_held', 'Средства заблокированы'), ('shipped', 'Товар отправлен'), ('delivered', 'Доставлено'), ('completed', 'Завершено'), ('timeout_refunded', 'Возврат по таймауту'), ('cancelled', 'Отменено'), ('disputed', 'Спор')], default='waiting_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('track_number', models.CharField(blank=True, max_length=100)),
                ('shipping_service', models.CharField(default='pochta_russia', max_length=50)),
                ('delivery_address', models.TextField()),
                ('yookassa_payment_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_purchases', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='shop_app.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=100)),
                ('last_status', models.CharField(blank=True, max_length=100)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='shop_app.escrowtransaction')),
            ],
        ),
    ]
